# Use the official Node.js image as the base image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Install pnpm
RUN npm install -g pnpm

# Copy pnpm lockfile and package.json
COPY pnpm-lock.yaml ./
COPY package.json ./

# Install dependencies using pnpm
RUN pnpm install --production

# Copy the rest of your application code
COPY . .

# Build the NestJS application
RUN pnpm build

# Expose the application port
EXPOSE 3000

# Define the command to start the application
CMD ["node", "dist/main"]
