version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:latest
    container_name: postgres-server
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: mongodb-server
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  user-management:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-management
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb+srv://muhammadarslan6492:5DzvDRBvZ2MuFtMk@cluster0.nlk6u.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=yhasdhgajsgdjashgdjg
      - NODE_ENV=production

volumes:
  redis-data:
  postgres-data:
  mongo-data:
